# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fe4de8ceb9c4ffcdd77b4e8ff1521b6fd9d7ddb704ab5d74051e3ccf6e8e0dd9e7e8f21a2c0f5b70df6f7dce8ce1e8a52e0afa0b6c5a7c4275e210d144efc82b

test:
  secret_key_base: 1418dd8923c4e56075b5cc42a1a18a9593cde6240e5620ac8f4f086629f522e81ba4f9fceefbd7eb63bf04a83b86cdbff990b4bb41ae1c36d44796f4de574dbd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
