# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-28 23:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_auto_20160928_2120'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quotes',
            old_name='quotes_by',
            new_name='quoted_by',
        ),
    ]
