# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-05 22:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poke', '0002_auto_20161001_2032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poke',
            name='User_id',
        ),
        migrations.RemoveField(
            model_name='poke',
            name='poke',
        ),
    ]
