# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-05 22:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poke', '0003_auto_20161005_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='poke',
            name='pokee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='who_was_poked', to='poke.User'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='poke',
            name='poker',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='who_poked', to='poke.User'),
            preserve_default=False,
        ),
    ]
