# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1e7c765606c998966d15f632db9d3680f17408efbb9247dcdba9c26311836e7ab7c7e88fce1f04b80ffcf623c0d028b9ace354e9f9d60190963a33dbd2b55fb4

test:
  secret_key_base: b0127cee72cb0d28eef817c801ba17af31a4b50a66942d75c70b58c5019b94352589440fdf7b3813b322437f619d7c466622a9c6d71347143ffd2e3e1601df32

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
